[package]
version = "0.1.0"
name = "litmus-zk-program"
edition = "2021"

[build-dependencies]
sp1-build = "4.2.1"

[dependencies]
ltypeset = { path = "../crates/ltypeset" }
lverifiers = { path = "../crates/lverifiers" }
serde.workspace = true
serde_cbor.workspace = true
sp1-zkvm = "4.2.1"
